/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alkasabaproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class maneger extends javax.swing.JFrame {
 
    private String dbURL;
	private String dbUsername = "root";
	private String dbPassword = "1180070";
	private String URL = "127.0.0.1";
	private String port = "3306";
	private String dbName = "Alkasaba_cinema";
	private Connection con=null;
        PreparedStatement ps=null;
        ResultSet rst=null;
        
        PreparedStatement ps1=null;
        ResultSet rst1=null;
        
        PreparedStatement ps2=null;
        ResultSet rst2=null;
    /**
     * Creates new form maneger
     */
    public maneger() {
        initComponents();
        connection();
    }
private Connection connection()  {  //throws ClassNotFoundException, SQLException
		
	dbURL = "jdbc:mysql://" + URL + ":" + port + "/" + dbName + "?verifyServerCertificate=false";
	Properties p = new Properties();
	p.setProperty("user", dbUsername);
	p.setProperty("password", dbPassword);
	p.setProperty("useSSL", "false");
	p.setProperty("autoReconnect", "true");
	
	try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection (dbURL, p);
            //JOptionPane.showMessageDialog(null,"conncted");
            return con;
        }
		
        catch (SQLException ex){
           // Logger.getLogger(Foodmenu.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"not conncted1");
            return null;
        }
        catch (ClassNotFoundException ex1){
           // Logger.getLogger(Foodmenu.class.getName()).log(Level.SEVERE, null, ex1);
            JOptionPane.showMessageDialog(null,"not conncted2");
            return null;
        }
    }

    public boolean checkinputs(){
        if (ssn.getText() == null || name.getText() == null || phone.getText() == null ||email.getText() == null || 
                job.getText() == null  ||address.getText() == null  ||hours.getText() == null || wage.getText() == null){
            return false;
        }
        else{
            try{
                Integer.parseInt(ssn.getText());
                Integer.parseInt(phone.getText());
                Float.parseFloat(hours.getText());
                Float.parseFloat(wage.getText());
                return true;
            }
            catch (Exception ex){
                return false;
            }
        }
    }
    
    public boolean checkinputsC2() {
        if (ssn1.getText() == null || Name.getText() == null || Phone.getText() == null || EMAIL.getText() == null
                || ADDRESS.getText() == null) {
            return false;
        } else {
            try {
                Integer.parseInt(ssn1.getText());
                Integer.parseInt(Phone.getText());
                return true;
            } catch (Exception ex) {
                return false;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AllSalary = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        CafeteriaEmployee = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ssn1 = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        EMAIL = new javax.swing.JTextField();
        ADDRESS = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Chours = new javax.swing.JTextField();
        Cwage = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        CenimaEmployee = new javax.swing.JPanel();
        CenEDisplay = new javax.swing.JButton();
        percent = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        ssn = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        job = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        hours = new javax.swing.JTextField();
        wage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        employee_name = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AllSalary.setIcon(new javax.swing.ImageIcon("C:\\1202\\Database\\AlkasabaProject\\icons8-money-24.png")); // NOI18N
        AllSalary.setLabel("Salaries in Month");
        AllSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllSalaryActionPerformed(evt);
            }
        });
        jPanel1.add(AllSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 190, 30));

        jTabbedPane1.setName(""); // NOI18N

        jButton2.setText("Display Employees");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("SSN");

        jLabel11.setText("Name");

        jLabel12.setText("Phone ");

        jLabel13.setText("Email");

        jLabel14.setText("Address");

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        jButton6.setText("Delete by SSN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("Update Employee");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel15.setText("Hours Worked");

        jLabel16.setText("Hourly Wage");

        jButton9.setText("Add cashier");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel17.setText("Salary");

        jButton10.setText("Add Chef");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CafeteriaEmployeeLayout = new javax.swing.GroupLayout(CafeteriaEmployee);
        CafeteriaEmployee.setLayout(CafeteriaEmployeeLayout);
        CafeteriaEmployeeLayout.setHorizontalGroup(
            CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ssn1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CafeteriaEmployeeLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Phone))
                    .addComponent(jLabel3)
                    .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Chours, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton9)
                        .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Cwage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                        .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                        .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ADDRESS)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        CafeteriaEmployeeLayout.setVerticalGroup(
            CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CafeteriaEmployeeLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13)
                            .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ssn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Chours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Cwage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(CafeteriaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cafeteria Employee", CafeteriaEmployee);

        CenEDisplay.setText("Display Employees");
        CenEDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CenEDisplayActionPerformed(evt);
            }
        });

        percent.setToolTipText("");
        percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\1202\\Database\\AlkasabaProject\\icons8-loyalty-card-26.png")); // NOI18N
        jButton3.setLabel("Add bonus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ssn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ssnMouseExited(evt);
            }
        });
        ssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnActionPerformed(evt);
            }
        });

        hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursActionPerformed(evt);
            }
        });

        jLabel1.setText("SSN");

        jLabel2.setText("Name");

        jLabel5.setText("Phone ");

        jLabel6.setText("Email");

        jLabel7.setText("Job Description");

        jLabel8.setText("Address");

        jLabel9.setText("Hours Worked");

        jLabel10.setText("Hourly Waged");

        jButton1.setText("Add employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Update employee");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete by SSN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\1202\\Database\\AlkasabaProject\\src\\loupe.png")); // NOI18N
        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel18.setText("Enter Employee name");

        javax.swing.GroupLayout CenimaEmployeeLayout = new javax.swing.GroupLayout(CenimaEmployee);
        CenimaEmployee.setLayout(CenimaEmployeeLayout);
        CenimaEmployeeLayout.setHorizontalGroup(
            CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CenimaEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                        .addComponent(CenEDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                        .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                                .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(job, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                            .addComponent(address)))
                                    .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(12, 12, 12)
                                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hours, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(wage))
                        .addGap(40, 40, 40)))
                .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
            .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                        .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton3))
                    .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                        .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employee_name, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel18)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CenimaEmployeeLayout.setVerticalGroup(
            CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CenEDisplay)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jButton4))
                .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(job, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)))
                    .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(CenimaEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CenimaEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(employee_name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        percent.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Cenima Employee", CenimaEmployee);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 620, 330));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Cenima Employee");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        jButton11.setText("Report");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 410, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Captu3re.PNG")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1210, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void percentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         con = connection();
        float bonus = Float.parseFloat(percent.getText());
        //int bonus = Integer.parseInt(percent.getText());
        try{  //"+ bonus+"
        String sql = "UPDATE Cinema_Employees_manage\n" +
                        "SET \n" +
                        "   hourly_waged =hourly_waged+hourly_waged* "+ bonus+" \n" +
                        "where \n" +
                        " SSN >= 1";
        Statement ps1;

            ps1 = con.createStatement();//sql
             ps1.executeUpdate(sql);

        }catch(Exception ex){
        }finally{
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CenEDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CenEDisplayActionPerformed
        // TODO add your handling code here:
        TableCinema table = new TableCinema();
        table.setVisible(true);
    }//GEN-LAST:event_CenEDisplayActionPerformed

    private void AllSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllSalaryActionPerformed
        // TODO add your handling code here:
         con = connection();
        
        try{ 
        String sql = "select sum(30 * C.hours_worked * C.hourly_waged)as Total_salary_in_each_month from Cinema_Employees_manage C";
        ps = con.prepareStatement(sql);
        rst = ps.executeQuery();
        
        String sql1 = "select sum(30 * C.salary) as chefsSalary from chefs C";
        ps1 = con.prepareStatement(sql1);
        rst1 = ps1.executeQuery();
        
        String sql2 = "select sum(C.hours_worked *C.hourly_waged*30) as Total_salary_in_each_month\n" +
                        "from cashiers C";
        ps2 = con.prepareStatement(sql2);
        rst2 = ps2.executeQuery();
        
            while(rst.next() && rst1.next() && rst2.next()){
             float salary =rst.getFloat("Total_salary_in_each_month");
             
             float salary1 =rst1.getFloat("chefsSalary");
             float salary2 =rst2.getFloat("Total_salary_in_each_month");
             float all = salary + salary1 +salary2;
             JOptionPane.showMessageDialog(null,all);
            }
        }catch(Exception ex){
        }finally{
        }
    }//GEN-LAST:event_AllSalaryActionPerformed

    private void ssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnActionPerformed

    private void ssnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssnMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ssnMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           /* String mangID = "select SSN from Manger";
            try{
            ps = con.prepareStatement(mangID);
            ps.execute();
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        */
            if (checkinputs()){
            try{
            String sql = "insert into Cinema_Employees_manage values ('"+Integer.parseInt(ssn.getText())+"','"+name.getText()+"','"+Integer.parseInt(phone.getText())+"','"+email.getText()+"','"+
                    job.getText()+"','"+address.getText()+"','"+Float.parseFloat(hours.getText())+"','"+Float.parseFloat(wage.getText())+"','"+2345+"')";
                
            ps = con.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null,"Done insert");
            
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }
        else {
            JOptionPane.showMessageDialog(null,"one or more feilds are empty");
        }
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int ssn1= Integer.parseInt(ssn.getText());
        try{
            String sql = "select SSN from Cinema_Employees_manage where SSN = '"+ssn1+"'";
            ps = con.prepareStatement(sql);
            rst = ps.executeQuery();
            if(rst.next()){
                ps = con.prepareStatement("update Cinema_Employees_manage set EMP_name =' "+name.getText() +"' where SSN = '"+ssn1+"'");
                ps.execute();
                    
                ps = con.prepareStatement("update Cinema_Employees_manage set phone_number =' "+Integer.parseInt(phone.getText()) +"' where SSN = '"+ssn1+"'");
                ps.execute();
                    
                ps = con.prepareStatement("update Cinema_Employees_manage set email =' "+name.getText() +"' where SSN = '"+ssn1+"'");
                ps.execute();
                
                ps = con.prepareStatement("update Cinema_Employees_manage set job_description =' "+job.getText() +"' where SSN = '"+ssn1+"'");
                ps.execute();
           	
                ps = con.prepareStatement("update Cinema_Employees_manage set address =' "+address.getText() +"' where SSN = '"+ssn1+"'");
                ps.execute();
		 ps = con.prepareStatement("update Cinema_Employees_manage set hours_worked =' "+hours.getText() +"' where SSN = '"+ssn1+"'");
                ps.execute();
		 ps = con.prepareStatement("update Cinema_Employees_manage set hourly_waged =' "+wage.getText() +"' where SSN= '"+ssn1+"'");
                ps.execute();
                JOptionPane.showMessageDialog(null,"Update Done");
                
            }else{
                JOptionPane.showMessageDialog(null,"SSNt= "+ssn1+" does not found");
            }
        }catch(Exception ex){
        }finally{
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String Id = JOptionPane.showInputDialog(null, "Enter SSN");
        int ssn = Integer.parseInt(Id);
        try {
            String sql = "select SSN from Cinema_Employees_manage where SSN = '" + ssn + "'";
            ps = con.prepareStatement(sql);
            rst = ps.executeQuery();
            if (rst.next()) {
                ps = con.prepareStatement("delete from Cinema_Employees_manage where SSN = '" + ssn + "'");
                ps.execute();
                JOptionPane.showMessageDialog(null, "Delete Done");
               
            } else {
                JOptionPane.showMessageDialog(null, "id= " + ssn + " does not found");
            }
        } catch (Exception ex) {
        } finally {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TableCafateria cafe = new TableCafateria();
        cafe.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if (checkinputsC2()) {
            try {

                String sql = "insert into Cafeteria_Employees_manges values('" + Integer.parseInt(ssn1.getText()) + "','" + Name.getText() + "','" + Integer.parseInt(Phone.getText()) + "','" + EMAIL.getText() + "','"
                        + ADDRESS.getText() + "','" + 2345 + "')";

                ps = con.prepareStatement(sql);
                ps.execute();
                
                ps = con.prepareStatement("insert into chefs values('" + Integer.parseInt(ssn1.getText()) + "','" + Float.parseFloat(salary.getText())+"')");
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Done insert");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "one or more feilds are empty");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String Id = JOptionPane.showInputDialog(null, "Enter SSN");
        int ssn = Integer.parseInt(Id);
        try {
            String sql = "select SSN from Cafeteria_Employees_manges where SSN = '" + ssn + "'";
            ps = con.prepareStatement(sql);
            rst = ps.executeQuery();
            if (rst.next()) {
                ps = con.prepareStatement("delete from Cafeteria_Employees_manges where SSN = '" + ssn + "'");
                ps.execute();
                JOptionPane.showMessageDialog(null, "Delete Done");

            } else {
                JOptionPane.showMessageDialog(null, "SSN= " + ssn + " does not found");
            }
        } catch (Exception ex) {
        } finally {
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         int ssn = Integer.parseInt(ssn1.getText());
        try {
            String sql = "select SSN from Cafeteria_Employees_manges where SSN = '" + ssn + "'";
            ps = con.prepareStatement(sql);
            rst = ps.executeQuery();
            if (rst.next()) {
                ps = con.prepareStatement("update Cafeteria_Employees_manges set EMP_name =' " + Name.getText() + "' where SSN = '" + ssn + "'");
                ps.execute();

                ps = con.prepareStatement("update Cafeteria_Employees_manges set phone_number =' " + Integer.parseInt(Phone.getText()) + "' where SSN = '" + ssn + "'");
                ps.execute();

                ps = con.prepareStatement("update Cafeteria_Employees_manges set email =' " + EMAIL.getText() + "' where SSN = '" + ssn + "'");
                ps.execute();

                ps = con.prepareStatement("update Cafeteria_Employees_manges set address =' " + ADDRESS.getText() + "' where SSN = '" + ssn + "'");
                ps.execute();

                JOptionPane.showMessageDialog(null, "Update Done");

            } else {
                JOptionPane.showMessageDialog(null, "SSN= " + ssn + " does not found");
            }
        } catch (Exception ex) {
        } finally {
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (checkinputsC2()) {
            try {

                String sql = "insert into Cafeteria_Employees_manges values('" + Integer.parseInt(ssn1.getText()) + "','" + Name.getText() + "','" + Integer.parseInt(Phone.getText()) + "','" + EMAIL.getText() + "','"
                        + ADDRESS.getText() + "','" + 2345 + "')";

                ps = con.prepareStatement(sql);
                ps.execute();
                
                ps = con.prepareStatement("insert into cashiers values('" + Integer.parseInt(ssn1.getText()) + "','" + Float.parseFloat(Chours.getText())+ "','" + Float.parseFloat(Cwage.getText())+"')");
                ps.execute();
                
                JOptionPane.showMessageDialog(null, "Done insert");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "one or more feilds are empty");
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        con = connection();
        String employee = employee_name.getText();
        try {
            String sql = "select phone_number, job_description, hours_worked \n"
                    + "from Cinema_Employees_manage\n"
                    + "where \n"
                    + "     EMP_name = '" + employee + "'";
            ps = con.prepareStatement(sql);
            rst = ps.executeQuery();
            if (rst.next()) {
                int phonenumber = rst.getInt("phone_number");
                String jobDescription = rst.getString("job_description");
                int hoursWorked = rst.getInt("hours_worked");

                JOptionPane.showMessageDialog(null, "phone number is " + phonenumber + "\njob_description is " + jobDescription + "\n number of hours_worked is " + hoursWorked);
            }else {
                JOptionPane.showMessageDialog(null,"not found");
            }


        } catch (Exception ex) {
        } finally {
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        report rep = new report();
            rep.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maneger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maneger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maneger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maneger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maneger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADDRESS;
    private javax.swing.JButton AllSalary;
    private javax.swing.JPanel CafeteriaEmployee;
    private javax.swing.JButton CenEDisplay;
    private javax.swing.JPanel CenimaEmployee;
    private javax.swing.JTextField Chours;
    private javax.swing.JTextField Cwage;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField address;
    private javax.swing.JTextField email;
    private javax.swing.JTextField employee_name;
    private javax.swing.JTextField hours;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField job;
    private javax.swing.JTextField name;
    private javax.swing.JTextField percent;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField ssn;
    private javax.swing.JTextField ssn1;
    private javax.swing.JTextField wage;
    // End of variables declaration//GEN-END:variables
}
